name: BIOWATCH
channels:
  - conda-forge
  - bioconda

dependencies:
  # Core
  - python=3.11
  - pip
  - r-base

  # R packages
  - r-shiny
  - r-shinyWidgets
  - r-shinyjs
  - r-bslib
  - r-leaflet
  - r-data.table
  - r-tidyverse
  - r-rgbif
  - r-htmlwidgets
  - r-leaflet.extras
  - r-sf
  - r-wk
  - r-geojsonio
  - r-DT
  - r-future
  - r-promises
  - r-reticulate
  - r-digest

  # Bio tools
  - blast
  - crabs


